+incdir+../tests
+incdir+../tests/mocks
+incdir+../tests/integration
+incdir+../src/types
+incdir+../src/model
+incdir+../src/codec
+incdir+../src/core
+incdir+../src/adapter
+incdir+../src/integration
+incdir+../src/adapters/host_mem
+incdir+../src/adapters/net_packet
+incdir+@HOST_MEM_ROOT@/src
+incdir+@NET_PACKET_ROOT@/src
+incdir+@DPU_COMMON_ROOT@/src
+incdir+@NET_PACKET_ROOT@/src/core
+incdir+@NET_PACKET_ROOT@/src/common
+incdir+@NET_PACKET_ROOT@/src/protocols
../src/types/rdma_types_pkg.sv
../src/model/rdma_model_pkg.sv
../src/codec/rdma_codec_pkg.sv
../src/adapter/rdma_adapter_pkg.sv
../src/core/rdma_core_pkg.sv
../src/adapters/host_mem/rdma_host_mem_adapter_pkg.sv
../src/adapters/net_packet/rdma_net_packet_adapter_pkg.sv
../src/adapters/net_packet/rdma_net_packet_bridge.sv
@DPU_COMMON_ROOT@/src/dpu_resource_pkg.sv
../src/integration/rdma_dpu_env_pkg.sv
../tests/rdma_unit_test_pkg.sv
../tests/tb_top.sv
