+incdir+@HOST_MEM_ROOT@/src
@HOST_MEM_ROOT@/src/host_mem_pkg.sv
@HOST_MEM_ROOT@/src/host_mem_manager.sv

+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/types
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/agent
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/env
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/adapter
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/topology
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/switch
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/base
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/constraints
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/scenario
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/virtual
@PCIE_WORK_ROOT@/pcie_tl_vip/src/pcie_tl_if.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared/pcie_tl_bdf_utils_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared/pcie_tl_device_profile_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/topology/pcie_topology_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/pcie_tl_pkg.sv

+incdir+../tests
+incdir+../src/types
+incdir+../src/model
+incdir+../src/codec
+incdir+../src/core
+incdir+../src/tb
+incdir+../src/adapter
+incdir+../src/dev
+incdir+../src/adapters/pcie_work
+incdir+../tests/mocks
../src/types/rdma_types_pkg.sv
../src/model/rdma_model_pkg.sv
../src/codec/rdma_codec_pkg.sv
../src/adapter/rdma_adapter_pkg.sv
../src/dev/rdma_dev_pkg.sv
../src/core/rdma_core_pkg.sv
../src/tb/rdma_tb_pkg.sv
../src/adapters/pcie_work/rdma_pcie_work_adapter_pkg.sv
../tests/rdma_unit_test_pkg.sv
../tests/tb_top.sv
