+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/types
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/agent
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/env
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/adapter
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/topology
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/switch
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/base
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/constraints
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/scenario
+incdir+@PCIE_WORK_ROOT@/pcie_tl_vip/src/seq/virtual
@PCIE_WORK_ROOT@/pcie_tl_vip/src/pcie_tl_if.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared/pcie_tl_bdf_utils_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/shared/pcie_tl_device_profile_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/topology/pcie_topology_pkg.sv
@PCIE_WORK_ROOT@/pcie_tl_vip/src/pcie_tl_pkg.sv
+incdir+@PCIE_WORK_ROOT@/pcie_dpu_integration/src
@PCIE_WORK_ROOT@/pcie_dpu_integration/src/pcie_dpu_integration_pkg.sv

+incdir+../src/adapters/pcie_work
../src/adapters/pcie_work/rdma_pcie_work_pkg.sv
