+incdir+../src/types
+incdir+../src/model
+incdir+../src/codec
+incdir+../src/dev
+incdir+../src/drv
+incdir+../src/tb
+incdir+@HOST_MEM_ROOT@/src
+incdir+@NET_PACKET_ROOT@/src
+incdir+@NET_PACKET_ROOT@/src/core
+incdir+@NET_PACKET_ROOT@/src/common
+incdir+@NET_PACKET_ROOT@/src/protocols
@HOST_MEM_ROOT@/src/host_mem_pkg.sv
../src/types/rdma_types_pkg.sv
../src/model/rdma_model_pkg.sv
../src/codec/rdma_codec_pkg.sv
../src/adapters/host_mem/rdma_host_mem_pkg.sv
../src/dev/rdma_dev_pkg.sv
../src/drv/rdma_drv_pkg.sv
../src/adapters/dpu/rdma_dpu_adapter_pkg.sv
../src/adapters/net_packet/rdma_netpkt_pkg.sv
../src/tb/rdma_env_pkg.sv
