typedef enum bit [4:0] {
  RDMA_SC_OK,
  RDMA_SC_INVALID_ARGUMENT,
  RDMA_SC_INVALID_STATE,
  RDMA_SC_STALE_GENERATION,
  RDMA_SC_RESOURCE_EXHAUSTED,
  RDMA_SC_UNSUPPORTED_OPCODE,
  RDMA_SC_CODEC_ERROR,
  RDMA_SC_TIMEOUT,
  RDMA_SC_PCIE_COMPLETION,
  RDMA_SC_DMA_TRANSLATION,
  RDMA_SC_DMA_PERMISSION,
  RDMA_SC_QUEUE_FULL,
  RDMA_SC_QUEUE_EMPTY,
  RDMA_SC_UNKNOWN_HW_ERROR,
  RDMA_SC_RESET_CANCELLED
} rdma_status_code_e;

typedef enum bit [3:0] {
  RDMA_STATUS_NONE,
  RDMA_STATUS_CONFIGURATION,
  RDMA_STATUS_RESOURCE,
  RDMA_STATUS_STATE,
  RDMA_STATUS_CODEC,
  RDMA_STATUS_TIMEOUT,
  RDMA_STATUS_PCIE,
  RDMA_STATUS_DMA,
  RDMA_STATUS_QUEUE,
  RDMA_STATUS_HARDWARE,
  RDMA_STATUS_NETWORK,
  RDMA_STATUS_RESET
} rdma_status_category_e;

typedef enum bit [3:0] {
  RDMA_BIND_DISCOVERED,
  RDMA_BIND_PCIE_CONFIGURED,
  RDMA_BIND_BOUND,
  RDMA_BIND_PREPARED,
  RDMA_BIND_ACTIVE,
  RDMA_BIND_QUIESCING,
  RDMA_BIND_RESETTING,
  RDMA_BIND_RELEASED,
  RDMA_BIND_ERROR
} rdma_binding_state_e;

typedef enum bit [3:0] {
  RDMA_RESOURCE_FUNCTION,
  RDMA_RESOURCE_PD,
  RDMA_RESOURCE_MR,
  RDMA_RESOURCE_CQ,
  RDMA_RESOURCE_QP,
  RDMA_RESOURCE_SRQ,
  RDMA_RESOURCE_CMQ,
  RDMA_RESOURCE_CEQ,
  RDMA_RESOURCE_AEQ
} rdma_resource_kind_e;

typedef enum bit [2:0] {
  RDMA_TRANSPORT_RC,
  RDMA_TRANSPORT_UD,
  RDMA_TRANSPORT_URC,
  RDMA_TRANSPORT_CUSTOM,
  RDMA_TRANSPORT_RESERVED
} rdma_transport_e;

typedef enum bit [1:0] {
  RDMA_DMA_DEVICE_READ,
  RDMA_DMA_DEVICE_WRITE,
  RDMA_DMA_BIDIRECTIONAL
} rdma_dma_direction_e;

typedef enum bit [1:0] {
  RDMA_MAPPING_INVALID,
  RDMA_MAPPING_ACTIVE,
  RDMA_MAPPING_FROZEN,
  RDMA_MAPPING_RELEASED
} rdma_mapping_state_e;

typedef enum bit [4:0] {
  RDMA_IMAGE_NONE,
  RDMA_IMAGE_QPC,
  RDMA_IMAGE_CQC,
  RDMA_IMAGE_MRT,
  RDMA_IMAGE_SRQC,
  RDMA_IMAGE_CEQC,
  RDMA_IMAGE_AEQC,
  RDMA_IMAGE_CMQ_SQE,
  RDMA_IMAGE_CMQ_CQE,
  RDMA_IMAGE_SQE,
  RDMA_IMAGE_RQE,
  RDMA_IMAGE_CQE,
  RDMA_IMAGE_CEQE,
  RDMA_IMAGE_AEQE,
  RDMA_IMAGE_DOORBELL
} rdma_image_kind_e;

typedef enum bit [3:0] {
  RDMA_DOORBELL_CMQ_SQ,
  RDMA_DOORBELL_SQ,
  RDMA_DOORBELL_RQ,
  RDMA_DOORBELL_SRQ,
  RDMA_DOORBELL_CQ,
  RDMA_DOORBELL_CEQ,
  RDMA_DOORBELL_AEQ,
  RDMA_DOORBELL_QP_FLUSH,
  RDMA_DOORBELL_TQ_FLUSH
} rdma_doorbell_kind_e;

typedef enum bit [3:0] {
  RDMA_ENGINE_NONE,
  RDMA_ENGINE_RESOURCE,
  RDMA_ENGINE_CMQ,
  RDMA_ENGINE_SQ,
  RDMA_ENGINE_RQ,
  RDMA_ENGINE_CQ,
  RDMA_ENGINE_CEQ,
  RDMA_ENGINE_AEQ,
  RDMA_ENGINE_PCIE,
  RDMA_ENGINE_DMA,
  RDMA_ENGINE_NETWORK,
  RDMA_ENGINE_RESET
} rdma_engine_kind_e;

typedef enum bit [1:0] {
  RDMA_SEVERITY_INFO,
  RDMA_SEVERITY_WARNING,
  RDMA_SEVERITY_ERROR,
  RDMA_SEVERITY_FATAL
} rdma_severity_e;

typedef enum bit [1:0] {
  RDMA_RESPONDER_DUT,
  RDMA_RESPONDER_VIP,
  RDMA_RESPONDER_MONITOR_ONLY
} rdma_responder_mode_e;

typedef enum bit [1:0] {
  RDMA_RESET_FLR,
  RDMA_RESET_VF_DISABLE,
  RDMA_RESET_FUNCTION_RESET,
  RDMA_RESET_DUT_RESET
} rdma_reset_kind_e;

typedef enum bit [2:0] {
  RDMA_FAULT_WRONG_REQUESTER,
  RDMA_FAULT_IOVA_PERMISSION,
  RDMA_FAULT_CMQ_TIMEOUT,
  RDMA_FAULT_CQE_ERROR,
  RDMA_FAULT_PACKET_DROP,
  RDMA_FAULT_VF_FLR
} rdma_fault_kind_e;

typedef enum bit {
  RDMA_FUNCTION_PF,
  RDMA_FUNCTION_VF
} rdma_function_kind_e;

typedef enum bit {
  RDMA_ENDIAN_LITTLE,
  RDMA_ENDIAN_BIG
} rdma_byte_endian_e;
