// 目录：硬件编解码层 codec/rdma/rdma_defs.svh。
// 职责：提供可文本包含的宏、固定字段或掩码定义；不持有运行期对象。
// 依赖：依赖对应 codec package 的字段约定和编译期常量。
// 所有权与生命周期：宏/常量由包含它的编译单元拥有，生命周期为编译期。

// RDMA profile hardware definition baseline (external XTR v1 source), pinned by tools/check_rdma_profile_names.py.
// OFFSET is a pre-serialization logical qword bit coordinate:
//   WORD_BYTE_OFFSET * 8 + LSB.
// It is not a raw bit index in the big-endian byte image. Codecs must build
// each logical u64 with LSB/WIDTH, then serialize that qword big-endian.
`define RDMA_FIELD(STEM, WORD_BYTE, FIELD_LSB, FIELD_WIDTH) \
  localparam int unsigned STEM``_WORD_BYTE_OFFSET = WORD_BYTE; \
  localparam int unsigned STEM``_LSB = FIELD_LSB; \
  localparam int unsigned STEM``_WIDTH = FIELD_WIDTH; \
  localparam int unsigned STEM``_OFFSET = ((WORD_BYTE) * 8) + (FIELD_LSB);

localparam int unsigned RDMA_HW_VERSION = 1;
localparam int unsigned RDMA_QPC_BYTES = 512;
localparam int unsigned RDMA_CQC_BYTES = 64;
localparam int unsigned RDMA_CMQE_BYTES = 64;
localparam int unsigned RDMA_WQE_BYTES = 64;
localparam int unsigned RDMA_RQE_BYTES = 64;
localparam int unsigned RDMA_CQE_BYTES = 64;
// Variable CQE profiles accepted by the software codec facade.  Hardware
// images remain byte-addressed and must be aligned to the profile size.
localparam int unsigned RDMA_CQE_32B_BYTES = 32;
localparam int unsigned RDMA_CQE_64B_BYTES = 64;
localparam int unsigned RDMA_CQE_128B_BYTES = 128;
localparam int unsigned RDMA_CEQE_BYTES = 16;
localparam int unsigned RDMA_AEQE_BYTES = 16;
localparam int unsigned RDMA_DB_BYTES = 8;

localparam bit [63:0] RDMA_NOTIFY_WINDOW_OFFSET = 64'h2000;
localparam bit [63:0] RDMA_NOTIFY_WINDOW_SIZE = 64'h2000;
localparam bit [63:0] RDMA_DB_CMQ_OFFSET = 64'h000;
localparam bit [63:0] RDMA_DB_SQ_OFFSET = 64'h100;
localparam bit [63:0] RDMA_DB_RQ_OFFSET = 64'h010;
localparam bit [63:0] RDMA_DB_CQ_OFFSET = 64'h018;
localparam bit [63:0] RDMA_DB_CEQ_OFFSET = 64'h020;
localparam bit [63:0] RDMA_DB_AEQ_OFFSET = 64'h028;
localparam bit [63:0] RDMA_DB_CMQC_HIGH_OFFSET = 64'h030;
localparam bit [63:0] RDMA_DB_CMQC_LOW_OFFSET = 64'h038;
localparam bit [63:0] RDMA_DB_SRFQ_OFFSET = 64'h040;
localparam bit [63:0] RDMA_DB_RTS2SQD_OFFSET = 64'h048;
localparam bit [63:0] RDMA_DB_SQD2RTS_OFFSET = 64'h050;
localparam bit [63:0] RDMA_DB_QP_FLUSH_OFFSET = 64'h058;
localparam bit [63:0] RDMA_DB_TX_FLUSH_OFFSET = 64'h008;

localparam int unsigned RDMA_NOTIFY_SRQ_LIMIT_INVALID_VALUE = 1;
localparam int unsigned RDMA_NOTIFY_SRQ_PI_INVALID_VALUE = 1;
localparam int unsigned RDMA_DB_TYPE_QP_FLUSH = 4'ha;
localparam int unsigned RDMA_DB_TYPE_TX_FLUSH = 4'hb;
localparam int unsigned RDMA_DB_TYPE_RTS2SQD = 4'hd;
localparam int unsigned RDMA_DB_TYPE_SQD2RTS = 4'he;
localparam int unsigned RDMA_TX_FLUSH_DST_PORT = 4'hf;

localparam bit [7:0] RDMA_OP_QPC_CREATE = 8'h00;
localparam bit [7:0] RDMA_OP_QPC_MODIFY = 8'h01;
localparam bit [7:0] RDMA_OP_QPC_DELETE = 8'h02;
localparam bit [7:0] RDMA_OP_QPC_QUERY = 8'h03;
localparam bit [7:0] RDMA_OP_KEY_ALLOC = 8'h04;
localparam bit [7:0] RDMA_OP_MR_REGISTER = 8'h05;
localparam bit [7:0] RDMA_OP_MR_DEREGISTER = 8'h06;
localparam bit [7:0] RDMA_OP_MW_ALLOC = 8'h07;
localparam bit [7:0] RDMA_OP_MW_DEALLOC = 8'h08;
localparam bit [7:0] RDMA_OP_KEY_QUERY = 8'h09;
localparam bit [7:0] RDMA_OP_OCC_FLUSH = 8'h0a;
localparam bit [7:0] RDMA_OP_CQC_RESIZE = 8'h0b;
localparam bit [7:0] RDMA_OP_CQC_CREATE = 8'h0c;
localparam bit [7:0] RDMA_OP_CQC_MODIFY = 8'h0d;
localparam bit [7:0] RDMA_OP_CQC_DELETE = 8'h0e;
localparam bit [7:0] RDMA_OP_CQC_QUERY = 8'h0f;
localparam bit [7:0] RDMA_OP_CEQC_CREATE = 8'h10;
localparam bit [7:0] RDMA_OP_CEQC_MODIFY = 8'h11;
localparam bit [7:0] RDMA_OP_CEQC_DELETE = 8'h12;
localparam bit [7:0] RDMA_OP_CEQC_QUERY = 8'h13;
localparam bit [7:0] RDMA_OP_AEQC_CREATE = 8'h14;
localparam bit [7:0] RDMA_OP_AEQC_MODIFY = 8'h15;
localparam bit [7:0] RDMA_OP_AEQC_DELETE = 8'h16;
localparam bit [7:0] RDMA_OP_AEQC_QUERY = 8'h17;
localparam bit [7:0] RDMA_OP_SD_UPDATE = 8'h18;
localparam bit [7:0] RDMA_OP_SD_QUERY = 8'h19;
localparam bit [7:0] RDMA_OP_QP_FLUSH = 8'h1a;
localparam bit [7:0] RDMA_OP_SRC_ADDR_UPDATE = 8'h1b;
localparam bit [7:0] RDMA_OP_SRC_ADDR_QUERY = 8'h1c;
localparam bit [7:0] RDMA_OP_STAT_QUERY = 8'h1d;
localparam bit [7:0] RDMA_OP_QPC_FORCE_DELETE = 8'h1e;
localparam bit [7:0] RDMA_OP_CQC_FORCE_DELETE = 8'h1f;
localparam bit [7:0] RDMA_OP_TQ_FLUSH = 8'h20;
localparam bit [7:0] RDMA_OP_OCC_QPC = 8'h21;
localparam bit [7:0] RDMA_OP_OCC_CQC = 8'h22;
localparam bit [7:0] RDMA_OP_OCC_MRT = 8'h23;
localparam bit [7:0] RDMA_OP_OCC_PBLE = 8'h24;
localparam bit [7:0] RDMA_OP_OCC_SQRQE = 8'h25;
localparam bit [7:0] RDMA_OP_OCC_SGB = 8'h26;
localparam bit [7:0] RDMA_OP_OCC_IRQE = 8'h27;
localparam bit [7:0] RDMA_OP_OCC_EIRQE = 8'h28;
localparam bit [7:0] RDMA_OP_OCC_ORQE = 8'h29;
localparam bit [7:0] RDMA_OP_OCC_UAQE = 8'h2a;
localparam bit [7:0] RDMA_OP_IDX_OCC_QPC = 8'h2b;
localparam bit [7:0] RDMA_OP_IDX_OCC_CQC = 8'h2c;
localparam bit [7:0] RDMA_OP_IDX_OCC_MRT = 8'h2d;
localparam bit [7:0] RDMA_OP_IDX_OCC_PBLE = 8'h2e;
localparam bit [7:0] RDMA_OP_IDX_OCC_SQRQE = 8'h2f;
localparam bit [7:0] RDMA_OP_IDX_OCC_SGB = 8'h30;
localparam bit [7:0] RDMA_OP_IDX_OCC_IRQE = 8'h31;
localparam bit [7:0] RDMA_OP_IDX_OCC_EIRQE = 8'h32;
localparam bit [7:0] RDMA_OP_IDX_OCC_ORQE = 8'h33;
localparam bit [7:0] RDMA_OP_IDX_OCC_UAQE = 8'h34;
localparam bit [7:0] RDMA_OP_SRFQC_CREATE = 8'h35;
localparam bit [7:0] RDMA_OP_SRFQC_MODIFY = 8'h36;
localparam bit [7:0] RDMA_OP_SRFQC_DELETE = 8'h37;
localparam bit [7:0] RDMA_OP_SRFQC_QUERY = 8'h38;
localparam bit [7:0] RDMA_OP_IFA_UPDATE = 8'h39;
localparam bit [7:0] RDMA_OP_IFA_QUERY = 8'h3a;
localparam bit [7:0] RDMA_OP_OCC_QPC_KICKOUT = 8'h3b;
localparam bit [7:0] RDMA_OP_OCC_CQC_KICKOUT = 8'h3c;
localparam bit [7:0] RDMA_OP_OCC_MRT_KICKOUT = 8'h3d;
localparam bit [7:0] RDMA_OP_OCC_PBLE_KICKOUT = 8'h3e;
localparam bit [7:0] RDMA_OP_OCC_SQRQE_KICKOUT = 8'h3f;
localparam bit [7:0] RDMA_OP_OCC_SGB_KICKOUT = 8'h40;
localparam bit [7:0] RDMA_OP_OCC_IRQE_KICKOUT = 8'h41;
localparam bit [7:0] RDMA_OP_OCC_EIRQE_KICKOUT = 8'h42;
localparam bit [7:0] RDMA_OP_OCC_ORQE_KICKOUT = 8'h43;
localparam bit [7:0] RDMA_OP_OCC_UAQE_KICKOUT = 8'h44;
localparam bit [7:0] RDMA_OP_NOP = 8'h45;
localparam bit [7:0] RDMA_OP_OCC_PD_SEARCH = 8'h46;
localparam bit [7:0] RDMA_OP_OCC_PD_IDX_SEARCH = 8'h47;
localparam bit [7:0] RDMA_OP_OCC_PD_KICKOUT = 8'h48;

// SQ transport opcode values from xtrdma_wqe_opcode_map_table.
localparam bit [3:0] RDMA_SQ_OPCODE_SEND = 4'd1;
localparam bit [3:0] RDMA_SQ_OPCODE_SEND_WITH_IMM = 4'd2;
localparam bit [3:0] RDMA_SQ_OPCODE_SEND_WITH_INV = 4'd3;
localparam bit [3:0] RDMA_SQ_OPCODE_WRITE = 4'd4;
localparam bit [3:0] RDMA_SQ_OPCODE_WRITE_WITH_IMM = 4'd5;
localparam bit [3:0] RDMA_SQ_OPCODE_READ = 4'd6;
localparam bit [3:0] RDMA_SQ_OPCODE_ATOMIC_CMP_AND_SWP = 4'd7;
localparam bit [3:0] RDMA_SQ_OPCODE_ATOMIC_FETCH_AND_ADD = 4'd8;
localparam bit [3:0] RDMA_SQ_OPCODE_LOCAL_INV = 4'd14;

localparam int unsigned RDMA_QPC_MODIFY_STATE_ONLY = 0;
localparam int unsigned RDMA_QPC_MODIFY_FULL = 1;
localparam int unsigned RDMA_QPC_MODIFY_PARTIAL = 2;

// Driver-derived context object, state, mode, and access-right codes.
localparam int unsigned RDMA_ALLOC_TYPE_DIRECT = 0;
localparam int unsigned RDMA_ALLOC_TYPE_INDIRECT = 1;
localparam int unsigned RDMA_ALLOC_TYPE_HUGE = 2;
localparam int unsigned RDMA_ALLOC_TYPE_L3_INDIRECT = 3;
localparam int unsigned RDMA_ADDR_TYPE_VA_BASED = 0;
localparam int unsigned RDMA_ADDR_TYPE_ZERO_BASED = 1;
localparam int unsigned RDMA_MR_ST_INVALID = 0;
localparam int unsigned RDMA_MR_ST_FREE = 1;
localparam int unsigned RDMA_MR_ST_VALID = 2;
localparam int unsigned RDMA_HOST_PAGE_4K = 0;
localparam int unsigned RDMA_HOST_PAGE_2M = 1;
localparam int unsigned RDMA_HOST_PAGE_1G = 2;
localparam int unsigned RDMA_PBL_MODE_0 = 0;
localparam int unsigned RDMA_PBL_MODE_1 = 1;
localparam int unsigned RDMA_PBL_MODE_2 = 2;
localparam int unsigned RDMA_MEM_TYPE_MR = 0;
localparam int unsigned RDMA_MEM_TYPE_MW_TYPE1 = 1;
localparam int unsigned RDMA_MEM_TYPE_MW_TYPE2B = 2;
localparam int unsigned RDMA_INVALIDATE_DISABLE = 0;
localparam int unsigned RDMA_INVALIDATE_ENABLE = 1;
localparam int unsigned RDMA_CQC_ARM_ST_NO_EVENT = 0;
localparam int unsigned RDMA_CQC_ARM_ST_NEXT_SE = 1;
localparam int unsigned RDMA_CQC_ARM_ST_NEXT_COMP = 2;
localparam int unsigned RDMA_CQC_ST_INVALID = 0;
localparam int unsigned RDMA_CQC_ST_VALID = 1;
localparam int unsigned RDMA_CQC_ST_ERROR = 2;
localparam int unsigned RDMA_SRQC_ST_INVALID = 0;
localparam int unsigned RDMA_SRQC_ST_VALID = 1;
localparam int unsigned RDMA_SRQC_ST_ERROR = 2;
localparam int unsigned RDMA_EQC_ST_INVALID = 0;
localparam int unsigned RDMA_EQC_ST_VALID = 1;
localparam int unsigned RDMA_EQC_ST_ERROR = 2;
localparam bit [4:0] RDMA_RIGHT_LOCAL_WRITE = 5'h01;
localparam bit [4:0] RDMA_RIGHT_REMOTE_READ = 5'h02;
localparam bit [4:0] RDMA_RIGHT_REMOTE_WRITE = 5'h04;
localparam bit [4:0] RDMA_RIGHT_BIND_WINDOW = 5'h08;
localparam bit [4:0] RDMA_RIGHT_REMOTE_ATOMIC = 5'h10;

// CMQ completion success is profile-specific and is not a driver-source alias.
localparam bit [7:0] RDMA_CMQ_SUCCESS_ECODE = 8'h00;

// Complete source-identity mapping from pinned defs.h and wr.h error codes.
localparam bit [7:0] RDMA_ECODE_EC_TPE_DB_TYPE_INVLD = 8'h02;
localparam bit [7:0] RDMA_ECODE_EC_TPE_OCC_QPC_ERR = 8'h05;
localparam bit [7:0] RDMA_ECODE_EC_TPE_TX_FLUSH = 8'h07;
localparam bit [7:0] RDMA_ECODE_EC_TPE_QP_FLUSH = 8'h08;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_VF_QPN_UNMATCH = 8'h10;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_RTO_OVERTIME = 8'h16;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_SIGN_ERR_OVERTIME = 8'h17;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_PSN_ERR_OVERTIME = 8'h18;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_KEY_ERR = 8'h19;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_WQE_OPCODE_INVLD = 8'h1b;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_QP_ACCESS_ERR = 8'h1e;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_WQE_SIGN_ERR = 8'h1f;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_RETRY_FENCE_WQE = 8'h20;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_PAYLOAD_LEN_ABOVE = 8'h29;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_WRITE_LEN_UNMATCH = 8'h2a;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SGB_KEY_ERR = 8'h2b;
localparam bit [7:0] RDMA_ECODE_EC_RTS2SQD_DB_QP_ST_UNMATCH = 8'h2c;
localparam bit [7:0] RDMA_ECODE_EC_RTS2SQD_DONE = 8'h2e;
localparam bit [7:0] RDMA_ECODE_EC_SQD2RTS_DB_QP_ST_UNMATCH = 8'h2f;
localparam bit [7:0] RDMA_ECODE_EC_TPE_EIRQ_RDSQ_VF_QPN_UNMATCH = 8'h30;
localparam bit [7:0] RDMA_ECODE_EC_TPE_EIRQ_RDSQ_KEY_ERR = 8'h36;
localparam bit [7:0] RDMA_ECODE_EC_TPE_EIRQ_RDSQ_WQE_OPCODE_INVLD = 8'h38;
localparam bit [7:0] RDMA_ECODE_EC_TPE_URC_RSQ_RTO_OVERTIME = 8'h3a;
localparam bit [7:0] RDMA_ECODE_EC_TPE_TX_LOCAL_WQE_RTO_OVERTIME = 8'h3b;
localparam bit [7:0] RDMA_ECODE_EC_TPE_SQ_SGE_PLD_LEN_UNMATCH = 8'h3d;
localparam bit [7:0] RDMA_ECODE_EC_TME_OCC_MR_ABNORMAL_RSLT = 8'h44;
localparam bit [7:0] RDMA_ECODE_EC_TME_PBL_INVLD = 8'h45;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_LEN_ZERO = 8'h48;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_ST_ERR = 8'h49;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_TYPE_ERR = 8'h4a;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_PD_ERR = 8'h4b;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_KEY_ERR = 8'h4c;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_TYPE1_NOT_VA = 8'h4d;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_MR_LEN_ZERO = 8'h4e;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_LEN_ERR = 8'h4f;
localparam bit [7:0] RDMA_ECODE_EC_TME_PKT_TYPE2B_QPN_ERR = 8'h50;
localparam bit [7:0] RDMA_ECODE_EC_TME_PLD_LEN_CHK_ERR = 8'h51;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_NOT_PERMIT = 8'h52;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_ST_INVLD = 8'h53;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_TYPE1_MW = 8'h54;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_PD_ERR = 8'h55;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_KEY_ERR = 8'h56;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_MR_WITH_MW = 8'h57;
localparam bit [7:0] RDMA_ECODE_EC_TME_LOINVLD_TYPE2B_QPN_ERR = 8'h58;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_ST_NOT_VLD = 8'h5a;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_ST_INVLD = 8'h5b;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_ST_NOT_FREE = 8'h5c;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_TYPE_ERR = 8'h5d;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_TYPE_ERR = 8'h5e;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_WQE_TYPE_ERR = 8'h5f;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PD_ERR = 8'h60;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_KEY_ERR = 8'h61;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_RIGHT_B_ERR = 8'h62;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_RIGHT_LW_ERR = 8'h63;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_NOT_VA = 8'h64;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_LEN_ERR = 8'h65;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_TYPE1_OP_ERR = 8'h66;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_MW_TYPE2B_ZERO_BIND = 8'h67;
localparam bit [7:0] RDMA_ECODE_EC_TME_BIND_PARENT_MR_BIND_NUM_ERR = 8'h68;
localparam bit [7:0] RDMA_ECODE_EC_TME_FMR_ST_ERR = 8'h6c;
localparam bit [7:0] RDMA_ECODE_EC_TME_FMR_TYPE_ERR = 8'h6d;
localparam bit [7:0] RDMA_ECODE_EC_TME_FMR_PD_ERR = 8'h6e;
localparam bit [7:0] RDMA_ECODE_EC_TDE_DMA_ERR = 8'h70;
localparam bit [7:0] RDMA_ECODE_EC_TDE_SRC_ADDR_TBL_INVLD = 8'h72;
localparam bit [7:0] RDMA_ECODE_EC_CCE_RC_CCREQ = 8'h74;
localparam bit [7:0] RDMA_ECODE_EC_CCE_RC_ACK = 8'h75;
localparam bit [7:0] RDMA_ECODE_EC_CCE_URC_ACK = 8'h76;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_SRFQ_OVER_LIMIT_TH = 8'h78;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_SRFQ_PKT_LEN_UNMATCH_SGE = 8'h79;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_SRFQ_WQE_ERR = 8'h7a;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_SRFQ_ST_INVLD = 8'h7b;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_DUP_DR_NML_URC = 8'h7c;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_DR_OWN_URC = 8'h7d;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RC_URC_ACCESS_INVLD = 8'h7e;
localparam bit [7:0] RDMA_ECODE_EC_RPE_ICRC_ERR_TRIM_PKT = 8'h7f;
localparam bit [7:0] RDMA_ECODE_EC_RPE_OCC_QPC_ERR = 8'h85;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RC_URC_OPCODE_INVLD = 8'h8d;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RX_FLUSH = 8'h8f;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_RQ_WQE_ERR_UD = 8'h91;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_ATOMIC_OCTBYTE_ALIGN_ERR = 8'h94;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_OPCODE_MIS_LAST = 8'h95;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_OPCODE_MIS_FST = 8'h96;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_PKT_LEN_UNMATCH_PMTU_PAD = 8'h97;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_PKT_LEN_UNMATCH_RETH = 8'h98;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_PKT_LEN_UNMATCH_SGE_RC_URC = 8'h9c;
localparam bit [7:0] RDMA_ECODE_EC_RPE_REQ_RQ_WQE_ERR_RC_URC = 8'ha3;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_ORQ_WQE_ERR = 8'ha4;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_OPCODE_MIS_LAST = 8'ha8;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_OPCODE_MIS_FST = 8'ha9;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_PKT_LEN_UNMATCH_SGE_RC = 8'hab;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_PKT_LEN_UNMATCH_PMTU_PAD = 8'had;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_PSN_UNMATCH_ORQ_LAST_PSN = 8'hae;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_ORQE_PSN_ERR = 8'hb3;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RSP_NAK_RNR_ERR_OVERTIME = 8'hb7;
localparam bit [7:0] RDMA_ECODE_EC_RPE_NAK_FATAL_ERR = 8'hb9;
localparam bit [7:0] RDMA_ECODE_EC_RPE_RX_FLUSH_QP_INVLD = 8'hba;
localparam bit [7:0] RDMA_ECODE_EC_RPE_URC_DR_TCIE = 8'hbb;
localparam bit [7:0] RDMA_ECODE_EC_RPE_NACK_CIE = 8'hbc;
localparam bit [7:0] RDMA_ECODE_EC_RME_OCC_MR_ABNORMAL_RSLT = 8'hc4;
localparam bit [7:0] RDMA_ECODE_EC_RME_PBL_INVLD = 8'hc5;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_SRFQ_PD_ERR = 8'hc7;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_LEN_ZERO = 8'hc8;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_ST_ERR = 8'hc9;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_TYPE_ERR = 8'hca;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_PD_ERR = 8'hcb;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_KEY_ERR = 8'hcc;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_RIGHT_ERR = 8'hcd;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_TYPE1_NOT_VA = 8'hce;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_MR_LEN_ZERO = 8'hcf;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_LEN_ERR = 8'hd0;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_SRFQ_MR_ERR = 8'hd3;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_NOT_PERMIT = 8'hd4;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_ST_INVLD = 8'hd5;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_TYPE1_MW = 8'hd6;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_PD_ERR = 8'hd7;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_KEY_ERR = 8'hd8;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_MR_WITH_MW = 8'hd9;
localparam bit [7:0] RDMA_ECODE_EC_RME_ROINVLD_TYPE2B_QPN_ERR = 8'hda;
localparam bit [7:0] RDMA_ECODE_EC_RME_PKT_TYPE2B_QPN_ERR = 8'hdb;
localparam bit [7:0] RDMA_ECODE_EC_RME_PLD_LEN_CHK_ERR = 8'hdc;
localparam bit [7:0] RDMA_ECODE_EC_RCE_OCC_EIRQ_RDSQ_ERR = 8'he0;
localparam bit [7:0] RDMA_ECODE_EC_RCE_OCC_UAQ_ERR = 8'he7;
localparam bit [7:0] RDMA_ECODE_EC_RCE_URC_TACK_RBM_DUP_PKT = 8'he8;
localparam bit [7:0] RDMA_ECODE_EC_RCE_OCC_CQC_ERR = 8'hf2;
localparam bit [7:0] RDMA_ECODE_EC_RCE_CQC_INVLD = 8'hf3;
localparam bit [7:0] RDMA_ECODE_EC_RCE_CQ_FULL = 8'hf4;
localparam bit [7:0] RDMA_ECODE_EC_RCE_CQ_LOAD_PBA_ERR = 8'hf5;
localparam bit [7:0] RDMA_ECODE_EC_RCE_COM_EST = 8'hf6;
localparam bit [7:0] RDMA_ECODE_EC_RCE_CEQC_INVLD = 8'hf7;
localparam bit [7:0] RDMA_ECODE_EC_RCE_CEQ_FULL = 8'hf8;
localparam bit [7:0] RDMA_ECODE_EC_RCE_AEQC_INVLD = 8'hfa;
localparam bit [7:0] RDMA_ECODE_EC_RCE_AEQ_FULL = 8'hfb;
localparam bit [7:0] RDMA_ECODE_EC_GLB_MBUS_ERR = 8'hff;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_TX_REQ_NML = 8'h00;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_TX_RSP_NML = 8'h01;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_SQ_FLUSH_ERR = 8'h08;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_TX_EC_CCE_URC_ACK = 8'h76;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_SRFQ_OVER_LIMIT_TH = 8'h78;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_RX_REQ_NML = 8'h80;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_RX_RSP_NML = 8'h81;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_RQ_FLUSH_ERR = 8'h8f;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_NAK_FATAL_ERR = 8'hb9;
localparam bit [7:0] RDMA_ECODE_XTRDMA_CQE_ECODE_TX_EC_RCE_URC_SQ_CPL_SRBM_DUP_PKT = 8'hf0;

// QPC logical qwords.
`RDMA_FIELD(RDMA_QPC_TVER, 0, 62, 2)
`RDMA_FIELD(RDMA_QPC_MIG, 0, 61, 1)
`RDMA_FIELD(RDMA_QPC_SERVICE_TYPE, 0, 58, 3)
`RDMA_FIELD(RDMA_QPC_HOST_ID, 0, 52, 3)
`RDMA_FIELD(RDMA_QPC_VF_ID, 0, 40, 12)
`RDMA_FIELD(RDMA_QPC_ICOS, 0, 37, 3)
`RDMA_FIELD(RDMA_QPC_QPN, 0, 16, 21)
`RDMA_FIELD(RDMA_QPC_STAT_IDX, 0, 8, 8)
`RDMA_FIELD(RDMA_QPC_UD_QKEY_H, 0, 0, 8)
`RDMA_FIELD(RDMA_QPC_UD_QKEY_L, 8, 40, 24)
`RDMA_FIELD(RDMA_QPC_URC_RSQ_PBA_H, 0, 0, 4)
`RDMA_FIELD(RDMA_QPC_URC_RSQ_PBA_L, 8, 16, 48)
`RDMA_FIELD(RDMA_QPC_PKEY, 8, 0, 16)
`RDMA_FIELD(RDMA_QPC_SHADOW_PBA, 16, 9, 55)
`RDMA_FIELD(RDMA_QPC_TX_ENDIAN_SWAP, 16, 6, 1)
`RDMA_FIELD(RDMA_QPC_RX_ENDIAN_SWAP, 16, 5, 1)
`RDMA_FIELD(RDMA_QPC_SQ_CE_EN, 16, 4, 1)
`RDMA_FIELD(RDMA_QPC_RA_FENCE, 16, 3, 1)
`RDMA_FIELD(RDMA_QPC_AA_FENCE, 16, 2, 1)
`RDMA_FIELD(RDMA_QPC_FC_EN, 16, 1, 1)
`RDMA_FIELD(RDMA_QPC_CC_TYPE, 24, 62, 2)
`RDMA_FIELD(RDMA_QPC_URC_RSQ_SIZE, 24, 59, 3)
`RDMA_FIELD(RDMA_QPC_QP_ST, 24, 56, 3)
`RDMA_FIELD(RDMA_QPC_PMTU, 24, 48, 3)
`RDMA_FIELD(RDMA_QPC_RNR_RETRY_TH, 24, 45, 3)
`RDMA_FIELD(RDMA_QPC_QP_SN, 24, 32, 8)
`RDMA_FIELD(RDMA_QPC_RC_SRFQ, 24, 31, 1)
`RDMA_FIELD(RDMA_QPC_RC_SRFQN, 24, 16, 15)
`RDMA_FIELD(RDMA_QPC_PD_IDX, 24, 0, 16)
`RDMA_FIELD(RDMA_QPC_QP_ACCESS_FLAG, 32, 0, 5)
`RDMA_FIELD(RDMA_QPC_URC_RDSQ_PBA, 32, 12, 52)
`RDMA_FIELD(RDMA_QPC_URC_RDSQ_SIZE, 32, 8, 3)
`RDMA_FIELD(RDMA_QPC_PSN_RETRY_TH, 40, 5, 3)
`RDMA_FIELD(RDMA_QPC_RTO_CODE, 40, 0, 5)
`RDMA_FIELD(RDMA_QPC_VLAN, 56, 63, 1)
`RDMA_FIELD(RDMA_QPC_IPV6, 56, 62, 1)
`RDMA_FIELD(RDMA_QPC_TUNNEL, 56, 61, 1)
`RDMA_FIELD(RDMA_QPC_LAG, 56, 60, 1)
`RDMA_FIELD(RDMA_QPC_FWD, 56, 58, 2)
`RDMA_FIELD(RDMA_QPC_DST_VPORT_ID, 56, 44, 11)
`RDMA_FIELD(RDMA_QPC_SRC_ADDR_IDX, 56, 32, 12)
`RDMA_FIELD(RDMA_QPC_DST_PORT, 56, 24, 4)
`RDMA_FIELD(RDMA_QPC_DST_QPN, 56, 0, 24)
`RDMA_FIELD(RDMA_QPC_DMAC, 64, 16, 48)
`RDMA_FIELD(RDMA_QPC_PRI, 64, 13, 3)
`RDMA_FIELD(RDMA_QPC_CFI, 64, 12, 1)
`RDMA_FIELD(RDMA_QPC_VLAN_ID, 64, 0, 12)
`RDMA_FIELD(RDMA_QPC_FLOW_LABEL, 72, 32, 20)
`RDMA_FIELD(RDMA_QPC_SRC_VPORT_ID, 72, 52, 11)
`RDMA_FIELD(RDMA_QPC_DSCP, 72, 26, 6)
`RDMA_FIELD(RDMA_QPC_ECN, 72, 24, 2)
`RDMA_FIELD(RDMA_QPC_HOPLIMIT, 72, 16, 8)
`RDMA_FIELD(RDMA_QPC_CUR_UDP_SPORT, 72, 0, 16)
localparam int unsigned RDMA_QPC_DEST_IP_BYTE_OFFSET = 80;
localparam int unsigned RDMA_QPC_DEST_IP_BYTES = 16;
`RDMA_FIELD(RDMA_QPC_URC_TX_RBSN, 96, 24, 24)
`RDMA_FIELD(RDMA_QPC_URC_TX_DBSN, 96, 0, 24)
`RDMA_FIELD(RDMA_QPC_URC_RX_RBSN, 128, 24, 24)
`RDMA_FIELD(RDMA_QPC_URC_RX_DBSN, 128, 0, 24)
`RDMA_FIELD(RDMA_QPC_RC_TPE_CUR_SQ_PSN, 160, 0, 24)
`RDMA_FIELD(RDMA_QPC_RC_LAST_READ_PSN, 208, 0, 24)
`RDMA_FIELD(RDMA_QPC_SQ_PBA, 216, 12, 52)
`RDMA_FIELD(RDMA_QPC_SQ_SIZE, 216, 8, 4)
`RDMA_FIELD(RDMA_QPC_SQ_OM, 216, 6, 2)
`RDMA_FIELD(RDMA_QPC_RC_EIRQ_PSN_MAX, 224, 24, 24)
`RDMA_FIELD(RDMA_QPC_URC_NXT_RDSQ_FETCH_NUM, 224, 16, 6)
`RDMA_FIELD(RDMA_QPC_URC_RX_SRBSN, 224, 24, 24)
`RDMA_FIELD(RDMA_QPC_EIRQ_CUR_SEND_PSN, 232, 0, 24)
`RDMA_FIELD(RDMA_QPC_URC_CUR_TX_DPSN, 232, 24, 24)
`RDMA_FIELD(RDMA_QPC_URC_CUR_TX_RPSN, 232, 0, 24)
`RDMA_FIELD(RDMA_QPC_EPSN_REQ, 288, 16, 24)
`RDMA_FIELD(RDMA_QPC_URC_RXED_DBSN, 296, 0, 24)
`RDMA_FIELD(RDMA_QPC_URC_RQ_SE_TH, 320, 20, 4)
`RDMA_FIELD(RDMA_QPC_URC_SQ_CE_TH, 320, 16, 4)
`RDMA_FIELD(RDMA_QPC_URC_TX_SRBSN, 328, 24, 24)
`RDMA_FIELD(RDMA_QPC_URC_MAX_TX_SRBSN, 328, 0, 24)
`RDMA_FIELD(RDMA_QPC_RC_PSN_MAX_RPE, 344, 32, 24)
`RDMA_FIELD(RDMA_QPC_RC_EPSN_RSP, 352, 16, 24)
`RDMA_FIELD(RDMA_QPC2_RC_EPSN_RSP, 376, 32, 24)
`RDMA_FIELD(RDMA_QPC_URC_CUR_DSQ_PBA_H, 384, 0, 40)
`RDMA_FIELD(RDMA_QPC_URC_CUR_DSQ_PBA_L, 392, 52, 12)
`RDMA_FIELD(RDMA_QPC_URC_NXT_DSQ_PBA, 392, 0, 52)
`RDMA_FIELD(RDMA_QPC_URC_TPE_RPSN_MAX, 400, 40, 24)
`RDMA_FIELD(RDMA_QPC_RC_PSN_MAX_TPE, 416, 40, 24)
`RDMA_FIELD(RDMA_QPC_URC_TPE_DPSN_MAX, 416, 40, 24)
`RDMA_FIELD(RDMA_QPC_URC_NXT_DSQ_FETCH_NUM, 416, 32, 6)
`RDMA_FIELD(RDMA_QPC_RC_RETRY_FPSN, 424, 0, 24)
`RDMA_FIELD(RDMA_QPC_RC_RETRY_PSN, 432, 0, 24)
// qp.h:186-248 RC/UD queue resources (RAM_x INFO_y Dz -> byte x*128+y*32+(3-z)*8; unions with URC).
`RDMA_FIELD(RDMA_QPC_RC_ORQ_PBA_H, 0, 0, 4)
`RDMA_FIELD(RDMA_QPC_RC_ORQ_PBA_L, 8, 16, 48)
`RDMA_FIELD(RDMA_QPC_QP1, 16, 0, 1)
`RDMA_FIELD(RDMA_QPC_RC_ORQ_SIZE, 24, 59, 3)
`RDMA_FIELD(RDMA_QPC_RQ_CQE_MODE, 24, 54, 2)
`RDMA_FIELD(RDMA_QPC_SQ_CQE_MODE, 24, 52, 2)
`RDMA_FIELD(RDMA_QPC_LOCAL_RNR_CODE, 24, 40, 5)
`RDMA_FIELD(RDMA_QPC_RC_EIRQ_PBA, 32, 12, 52)
`RDMA_FIELD(RDMA_QPC_RC_IRQ_SIZE, 32, 8, 3)
`RDMA_FIELD(RDMA_QPC_UAQ_IRQ_PBA, 40, 12, 52)
`RDMA_FIELD(RDMA_QPC_UAQ_SIZE, 40, 8, 3)
`RDMA_FIELD(RDMA_QPC_EIRQ_PBA_EXTRA, 48, 12, 52)
`RDMA_FIELD(RDMA_QPC_ACK_REQ_TH, 48, 4, 4)
`RDMA_FIELD(RDMA_QPC_SRQ_SN, 56, 28, 4)
`RDMA_FIELD(RDMA_QPC_SQ_CQN, 448, 20, 20)
`RDMA_FIELD(RDMA_QPC_RQ_CQN, 448, 0, 20)
`RDMA_FIELD(RDMA_QPC_LOAD_RQ_PI_TH, 480, 16, 8)
`RDMA_FIELD(RDMA_QPC_RQ_PBA, 496, 12, 52)
`RDMA_FIELD(RDMA_QPC_RQ_SIZE, 496, 8, 4)
`RDMA_FIELD(RDMA_QPC_RQ_OM, 496, 6, 2)

// 功能：固定 QPC runtime shadow 的硬件坐标和 readback ownership 边界。
// qp.h:20 将硬件 shadow 放在 byte 504；wr.h:35-38 明确声明
// HW_DROP_DB_CNT[54:48]、SW_RING_DB_CNT[38:32]、SQ_PI_WRAP[15]、
// SQ_PI[14:0] 四组可观察位。该掩码只供读回校验使用，软件编码器不得写入。
// 失败边界：未列入掩码的 qword63 位（包括 bit63）必须继续按 reserved 拒绝。
localparam int unsigned RDMA_QPC_RUNTIME_SHADOW_BYTE_OFFSET = 504;
localparam int unsigned RDMA_QPC_RUNTIME_SHADOW_QWORD_INDEX = 63;
localparam bit [63:0] RDMA_QPC_RUNTIME_SHADOW_READBACK_MASK =
  64'h007f_007f_0000_ffff;

// Driver cq.h: the CQC shadow area occupies bytes 48..55 of the 64-byte
// context slot.  CI information is the trailing 32-bit big-endian word;
// this offset is absolute within the context slot, not relative to the
// shadow-area view exposed by the lifecycle adapter.
localparam int unsigned RDMA_CQC_SHADOW_AREA_OFFSET = 48;
localparam int unsigned RDMA_CQC_SHADOW_AREA_SIZE = 8;
localparam int unsigned RDMA_CQC_SHADOW_CI_INFO_OFFSET = 4;
localparam int unsigned RDMA_CQC_RUNTIME_SHADOW_BYTE_OFFSET =
  RDMA_CQC_SHADOW_AREA_OFFSET + RDMA_CQC_SHADOW_CI_INFO_OFFSET;
localparam int unsigned RDMA_CQC_RUNTIME_SHADOW_BYTE_LENGTH = 4;
localparam int unsigned RDMA_CQC_RUNTIME_SHADOW_CI_WIDTH = 23;
localparam int unsigned RDMA_CQC_RUNTIME_SHADOW_WRAP_BIT = 23;

// CQC sparse body in final 64-byte CMQ WQE coordinates (local context +8).
`RDMA_FIELD(RDMA_CQC_BODY_CQN, 0, 0, 21)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_SD_PBA, 8, 0, 52)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_SIZE, 8, 56, 5)
`RDMA_FIELD(RDMA_CQC_BODY_URC_FLAG, 8, 61, 1)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_ST, 8, 62, 2)
`RDMA_FIELD(RDMA_CQC_BODY_NXT_CQ_PD_PBA_H, 16, 0, 8)
`RDMA_FIELD(RDMA_CQC_BODY_CUR_PBA_VLD, 16, 11, 1)
`RDMA_FIELD(RDMA_CQC_BODY_CUR_CQ_PD_PBA, 16, 12, 52)
`RDMA_FIELD(RDMA_CQC_BODY_LOAD_CQ_CI_DONE, 24, 0, 1)
`RDMA_FIELD(RDMA_CQC_BODY_LOAD_CQ_CI_TH, 24, 8, 3)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_OM, 24, 14, 2)
`RDMA_FIELD(RDMA_CQC_BODY_NXT_PBA_VLD, 24, 19, 1)
`RDMA_FIELD(RDMA_CQC_BODY_NXT_CQ_PD_PBA_L, 24, 20, 44)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_PI, 32, 0, 23)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_PI_WRAP, 32, 23, 1)
`RDMA_FIELD(RDMA_CQC_BODY_LAST_ARM_SN, 32, 60, 2)
`RDMA_FIELD(RDMA_CQC_BODY_CQE_SIZE, 32, 62, 2)
`RDMA_FIELD(RDMA_CQC_BODY_CEQN, 40, 0, 12)
`RDMA_FIELD(RDMA_CQC_BODY_SHADOW_PA, 48, 6, 58)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_CI, 56, 0, 23)
`RDMA_FIELD(RDMA_CQC_BODY_CQ_CI_WRAP, 56, 23, 1)
`RDMA_FIELD(RDMA_CQC_BODY_ARM_SN, 56, 32, 2)
`RDMA_FIELD(RDMA_CQC_BODY_ARM_ST, 56, 34, 2)
// CQC_RESIZE SQE (cmq.h XTRDMA_RESIZE_CQ_CMSQ_WQE_*); CQN shares RDMA_CQC_BODY_CQN.
`RDMA_FIELD(RDMA_CQC_RESIZE_CQ_SD_OR_PD_PBA, 8, 12, 52)
`RDMA_FIELD(RDMA_CQC_RESIZE_CQ_SIZE, 16, 59, 5)
`RDMA_FIELD(RDMA_CQC_RESIZE_CQ_OM, 16, 54, 2)
`RDMA_FIELD(RDMA_CQC_RESIZE_LOAD_CQ_CI_TH, 16, 51, 3)
`RDMA_FIELD(RDMA_CQC_RESIZE_OLD_CQ_CI_WRAP, 16, 47, 1)
`RDMA_FIELD(RDMA_CQC_RESIZE_OLD_CQ_CI, 16, 24, 23)

// CMQ control and command-specific fields.
`RDMA_FIELD(RDMA_CMQ_VALID, 0, 63, 1)
`RDMA_FIELD(RDMA_CMQ_VFID_OVERRIDE, 0, 59, 1)
`RDMA_FIELD(RDMA_CMQ_USE_VFID, 0, 48, 11)
`RDMA_FIELD(RDMA_CMQ_WRAP, 0, 45, 1)
`RDMA_FIELD(RDMA_CMQ_WQE_INDEX, 0, 40, 5)
`RDMA_FIELD(RDMA_CMQ_OPCODE, 0, 32, 8)
`RDMA_FIELD(RDMA_CMQ_CMD_ECODE, 0, 24, 8)
`RDMA_FIELD(RDMA_CMQ_NEXT_QP_STATE, 0, 60, 3)
`RDMA_FIELD(RDMA_CMQ_QPN, 0, 0, 24)
`RDMA_FIELD(RDMA_CMQ_SQ_CQN, 8, 43, 21)
`RDMA_FIELD(RDMA_CMQ_SIGN_EN, 8, 32, 1)
`RDMA_FIELD(RDMA_CMQ_SIGNATURE, 8, 24, 8)
`RDMA_FIELD(RDMA_CMQ_RQ_CQN, 8, 0, 21)
`RDMA_FIELD(RDMA_CMQ_MODIFY_MODE, 16, 62, 2)
`RDMA_FIELD(RDMA_CMQ_MODIFY_START_QWORD0, 16, 56, 6)
`RDMA_FIELD(RDMA_CMQ_MODIFY_WBE0, 16, 48, 8)
`RDMA_FIELD(RDMA_CMQ_WBE_TEMPLATE_COUNT, 16, 46, 2)
`RDMA_FIELD(RDMA_CMQ_MODIFY_START_QWORD1, 16, 40, 6)
`RDMA_FIELD(RDMA_CMQ_MODIFY_WBE1, 16, 32, 8)
`RDMA_FIELD(RDMA_CMQ_MODIFY_START_QWORD2, 16, 24, 6)
`RDMA_FIELD(RDMA_CMQ_MODIFY_WBE2, 16, 16, 8)
`RDMA_FIELD(RDMA_CMQ_MODIFY_START_QWORD3, 16, 8, 6)
`RDMA_FIELD(RDMA_CMQ_MODIFY_WBE3, 16, 0, 8)
`RDMA_FIELD(RDMA_CMQ_QPC_BUFFER_ADDR, 24, 9, 55)
`RDMA_FIELD(RDMA_CMQ_MODIFY_DATA0, 32, 0, 64)
`RDMA_FIELD(RDMA_CMQ_MODIFY_DATA1, 40, 0, 64)
`RDMA_FIELD(RDMA_CMQ_MODIFY_DATA2, 48, 0, 64)
`RDMA_FIELD(RDMA_CMQ_MODIFY_DATA3, 56, 0, 64)
`RDMA_FIELD(RDMA_CMQ_OCC_VF_FLUSH, 0, 61, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_MR_SERIAL_FLUSH, 0, 60, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_QPN, 0, 0, 21)
`RDMA_FIELD(RDMA_CMQ_OCC_QPC, 8, 63, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_CQC, 8, 62, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_MRT, 8, 61, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_PBLE, 8, 60, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_SQRQE, 8, 59, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_SGB_IRQE, 8, 58, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_EIRQE, 8, 57, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_ORQE, 8, 56, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_UAQE, 8, 55, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_PD, 8, 54, 1)
`RDMA_FIELD(RDMA_CMQ_OCC_MR_SERIAL, 8, 32, 12)
`RDMA_FIELD(RDMA_CMQ_OCC_PD_BACKING, 16, 12, 52)
`RDMA_FIELD(RDMA_CMQ_COMPLETION_RETURN_OCC_IDX, 0, 46, 12)
`RDMA_FIELD(RDMA_CMQ_COMPLETION_IFA_INFO, 8, 0, 59)

// cmq.h:59-81 / defs.h:307-309: HMC configuration values. IFA data is the 64-bit
// IFA_UPDATE "data" word; SD entries are {sd_idx qword, data qword} 16-byte chunks;
// PD/PBLE entries are big-endian page descriptors.
`RDMA_FIELD(RDMA_IFA_DATA_VALID, 0, 0, 1)
`RDMA_FIELD(RDMA_IFA_DATA_OBJ_MODE, 0, 1, 2)
`RDMA_FIELD(RDMA_IFA_DATA_OBJ_SIZE, 0, 3, 4)
`RDMA_FIELD(RDMA_IFA_DATA_OBJ_MOUNT, 0, 7, 28)
`RDMA_FIELD(RDMA_IFA_DATA_FVM_SOA, 0, 35, 23)
`RDMA_FIELD(RDMA_SD_ENTRY_IDX, 0, 0, 12)
`RDMA_FIELD(RDMA_SD_ENTRY_PA, 8, 12, 52)
`RDMA_FIELD(RDMA_SD_ENTRY_VF_ID, 8, 4, 8)
`RDMA_FIELD(RDMA_SD_ENTRY_VF_VALID, 8, 0, 1)
`RDMA_FIELD(RDMA_PD_ENTRY_PBA, 0, 12, 52)
`RDMA_FIELD(RDMA_PD_ENTRY_VF_ID, 0, 4, 8)
`RDMA_FIELD(RDMA_PD_ENTRY_VLD, 0, 0, 1)
localparam int unsigned RDMA_SD_ENTRY_BYTES = 16;
localparam int unsigned RDMA_SD_CARRIED_IN_SQE = 2;
localparam int unsigned RDMA_SD_MAX_PER_UPDATE = 34;
localparam int unsigned RDMA_HMC_FVM_SOA_SHIFT = 9;
localparam int unsigned RDMA_HMC_PAGE_BYTES = 4096;
localparam int unsigned RDMA_HMC_PD_PER_SD = 512;

// MRT sparse register/key-allocate body in final WQE coordinates.
`RDMA_FIELD(RDMA_MRT_BODY_STAG_IDX, 0, 0, 24)
`RDMA_FIELD(RDMA_MRT_BODY_NXT_ST, 0, 61, 2)
`RDMA_FIELD(RDMA_MRT_BODY_STAG_KEY, 8, 24, 8)
`RDMA_FIELD(RDMA_MRT_BODY_PARENT_STAG_IDX, 16, 0, 24)
`RDMA_FIELD(RDMA_MRT_BODY_PD_IDX, 16, 24, 16)
`RDMA_FIELD(RDMA_MRT_BODY_PLD_VF_ID, 16, 40, 8)
`RDMA_FIELD(RDMA_MRT_BODY_PLD_VF_EN, 16, 48, 1)
`RDMA_FIELD(RDMA_MRT_BODY_RIGHT, 16, 49, 5)
`RDMA_FIELD(RDMA_MRT_BODY_TYPE, 16, 54, 2)
`RDMA_FIELD(RDMA_MRT_BODY_HOST_PG_SIZE, 16, 56, 2)
`RDMA_FIELD(RDMA_MRT_BODY_PBL_MODE, 16, 58, 2)
`RDMA_FIELD(RDMA_MRT_BODY_ADDR_MODE, 16, 60, 1)
`RDMA_FIELD(RDMA_MRT_BODY_INVALIDATE_EN, 16, 61, 1)
`RDMA_FIELD(RDMA_MRT_BODY_ST, 16, 62, 2)
`RDMA_FIELD(RDMA_MRT_BODY_LEN, 24, 0, 46)
`RDMA_FIELD(RDMA_MRT_BODY_ODP, 24, 47, 1)
`RDMA_FIELD(RDMA_MRT_BODY_INFO_STAG_KEY, 24, 56, 8)
`RDMA_FIELD(RDMA_MRT_BODY_START_VA, 32, 0, 64)
`RDMA_FIELD(RDMA_MRT_BODY_FIRST_PBL_IDX, 40, 36, 28)
`RDMA_FIELD(RDMA_MRT_BODY_PAYLOAD_PBA0, 40, 12, 52)
`RDMA_FIELD(RDMA_MRT_BODY_MR_SN, 48, 0, 12)
`RDMA_FIELD(RDMA_MRT_BODY_PAYLOAD_PBA1, 48, 12, 52)

// SRQC sparse body in final WQE coordinates (local context +16).
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQN, 0, 0, 16)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_ST, 16, 62, 2)
`RDMA_FIELD(RDMA_SRQC_BODY_LOAD_SRFQ_PI_TH, 16, 52, 8)
`RDMA_FIELD(RDMA_SRQC_BODY_SHADOW_PA, 16, 0, 52)
`RDMA_FIELD(RDMA_SRQC_BODY_PD_IDX, 24, 48, 16)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_PBA, 32, 12, 52)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_SIZE, 32, 4, 4)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_OM, 32, 2, 2)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_PI_WRAP, 40, 31, 1)
`RDMA_FIELD(RDMA_SRQC_BODY_SRFQ_PI, 40, 16, 15)
`RDMA_FIELD(RDMA_SRQC_BODY_LIMIT_TH, 40, 2, 14)
`RDMA_FIELD(RDMA_SRQC_BODY_ARM_SN, 40, 0, 2)

// CEQC/AEQC share this sparse EQC body layout (local context +16).
`RDMA_FIELD(RDMA_EQC_BODY_EQN, 0, 0, 12)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_ST, 16, 62, 2)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_SIZE, 16, 52, 5)
`RDMA_FIELD(RDMA_EQC_BODY_NXT_EQ_PBA, 16, 0, 52)
`RDMA_FIELD(RDMA_EQC_BODY_CUR_EQ_PBA, 24, 12, 52)
`RDMA_FIELD(RDMA_EQC_BODY_CUR_PBA_VLD, 24, 11, 1)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_PI_WRAP, 32, 38, 1)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_PI, 32, 20, 18)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_OM, 32, 14, 2)
`RDMA_FIELD(RDMA_EQC_BODY_MSI_X_IDX, 40, 48, 16)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_CI_WRAP, 40, 18, 1)
`RDMA_FIELD(RDMA_EQC_BODY_EQ_CI, 40, 0, 18)

// SQE, RQE, CQE, CEQE and AEQE fields.
`RDMA_FIELD(RDMA_SQ_WQE_QPN, 0, 0, 21)
`RDMA_FIELD(RDMA_SQ_WQE_ICOS, 0, 21, 3)
`RDMA_FIELD(RDMA_SQ_WQE_QP_SN, 0, 24, 8)
`RDMA_FIELD(RDMA_SQ_WQE_OPCODE, 0, 32, 4)
`RDMA_FIELD(RDMA_SQ_WQE_DST_PORT, 0, 36, 4)
`RDMA_FIELD(RDMA_SQ_WQE_INDEX, 0, 40, 15)
`RDMA_FIELD(RDMA_SQ_WQE_WRAP, 0, 55, 1)
`RDMA_FIELD(RDMA_SQ_WQE_SIGN_EN, 0, 56, 1)
`RDMA_FIELD(RDMA_SQ_WQE_SE, 0, 57, 1)
`RDMA_FIELD(RDMA_SQ_WQE_FENCE, 0, 58, 2)
`RDMA_FIELD(RDMA_SQ_WQE_INLINE_LOCAL_QPC_RD, 0, 60, 1)
`RDMA_FIELD(RDMA_SQ_WQE_CE, 0, 61, 2)
`RDMA_FIELD(RDMA_SQ_WQE_VALID, 0, 63, 1)
`RDMA_FIELD(RDMA_SQ_WQE_SGB_PA, 32, 9, 55)
`RDMA_FIELD(RDMA_SQ_WQE_RC_TOTAL_PAYLOAD_LEN, 8, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_RC_IMMEDIATE, 8, 32, 32)
`RDMA_FIELD(RDMA_SQ_WQE_SIGNATURE, 16, 56, 8)
`RDMA_FIELD(RDMA_SQ_WQE_RC_SGE_NUM, 16, 48, 8)
`RDMA_FIELD(RDMA_SQ_WQE_RC_REMOTE_KEY, 16, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_RC_REMOTE_VA, 24, 0, 64)
// wr.h:42 and wr.c:xtrdma_fill_sq_sgb() use byte 0x28 only for URC READ
// external-SGB WQEs.  The low 40 bits of qword5 remain reserved.
`RDMA_FIELD(RDMA_SQ_WQE_URC_TOTAL_PKT_NUM, 40, 40, 24)
`RDMA_FIELD(RDMA_SQ_WQE_LOCAL_INVLD_STAG, 8, 32, 32)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_SGE_NUM, 16, 48, 8)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_R_KEY, 16, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_R_VA, 24, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_L_LEN, 32, 32, 32)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_L_KEY, 32, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_L_VA, 40, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_FAA_ADD_DATA, 48, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_CAS_SWAP_DATA, 48, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_ATOMIC_CAS_CMP_DATA, 56, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_IPV4, 48, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_IPV6_L, 48, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_IPV6_H, 56, 0, 64)
`RDMA_FIELD(RDMA_SQ_WQE_UD_HOPLIMIT, 40, 56, 8)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_QPN, 40, 32, 24)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_Q_KEY, 40, 0, 32)
`RDMA_FIELD(RDMA_SQ_WQE_UD_MC, 32, 8, 1)
`RDMA_FIELD(RDMA_SQ_WQE_UD_TRAFFIC_CLASS, 32, 0, 8)
`RDMA_FIELD(RDMA_SQ_WQE_UD_PRI, 24, 61, 3)
`RDMA_FIELD(RDMA_SQ_WQE_UD_CFI, 24, 60, 1)
`RDMA_FIELD(RDMA_SQ_WQE_UD_VLAN_ID, 24, 48, 12)
`RDMA_FIELD(RDMA_SQ_WQE_UD_PD_IDX, 24, 32, 16)
`RDMA_FIELD(RDMA_SQ_WQE_UD_FLOW_LABEL, 24, 12, 20)
`RDMA_FIELD(RDMA_SQ_WQE_UD_SRC_ADDR_IDX, 24, 0, 12)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DMAC, 16, 0, 48)
`RDMA_FIELD(RDMA_SQ_WQE_UD_SGE_NUM, 16, 48, 8)
`RDMA_FIELD(RDMA_SQ_WQE_UD_TOTAL_PAYLOAD_LEN, 8, 0, 14)
`RDMA_FIELD(RDMA_SQ_WQE_UD_DST_VPORT_ID, 8, 14, 11)
`RDMA_FIELD(RDMA_SQ_WQE_UD_FWD, 8, 26, 2)
`RDMA_FIELD(RDMA_SQ_WQE_UD_LAG, 8, 28, 1)
`RDMA_FIELD(RDMA_SQ_WQE_UD_TUNNEL, 8, 29, 1)
`RDMA_FIELD(RDMA_SQ_WQE_UD_IPV6, 8, 30, 1)
`RDMA_FIELD(RDMA_SQ_WQE_UD_VLAN, 8, 31, 1)
`RDMA_FIELD(RDMA_RQE_QPN, 0, 0, 24)
`RDMA_FIELD(RDMA_RQE_QP_SN, 0, 24, 8)
`RDMA_FIELD(RDMA_RQE_OPCODE, 0, 32, 4)
`RDMA_FIELD(RDMA_RQE_INDEX, 0, 40, 15)
`RDMA_FIELD(RDMA_RQE_WRAP, 0, 55, 1)
// wr.h:179, XTRDMA_QP_RQ_SIGN_EN is the receive-WQE signature selector.
// The driver forces it on for an external SGB, even when rq_sign_en is off.
`RDMA_FIELD(RDMA_RQE_SIGN_EN, 0, 56, 1)
`RDMA_FIELD(RDMA_RQE_VALID, 0, 63, 1)
`RDMA_FIELD(RDMA_RQE_PAYLOAD_LEN, 8, 0, 32)
`RDMA_FIELD(RDMA_RQE_SIGNATURE, 16, 56, 8)
`RDMA_FIELD(RDMA_RQE_SGE_NUM, 16, 48, 8)
// Driver wr.h: XTRDMA_QP_RQ_SGB_PA is the encoded physical address
// (physical PA >> XTRDMA_RQ_SGB_PA_SHIFT) in qword4 bits[63:9].
`RDMA_FIELD(RDMA_RQE_SGB_PA, 32, 9, 55)
`RDMA_FIELD(RDMA_CQE_POLARITY, 0, 63, 1)
`RDMA_FIELD(RDMA_CQE_QP_ST, 0, 60, 3)
`RDMA_FIELD(RDMA_CQE_RQ_CQE, 0, 59, 1)
`RDMA_FIELD(RDMA_CQE_SRFQ, 0, 58, 1)
`RDMA_FIELD(RDMA_CQE_SE, 0, 57, 1)
`RDMA_FIELD(RDMA_CQE_SIGN_EN, 0, 56, 1)
`RDMA_FIELD(RDMA_CQE_WQE_WRAP, 0, 55, 1)
`RDMA_FIELD(RDMA_CQE_WQE_INDEX, 0, 40, 15)
`RDMA_FIELD(RDMA_CQE_PKT_OPCODE, 0, 32, 8)
`RDMA_FIELD(RDMA_CQE_ECODE, 0, 24, 8)
`RDMA_FIELD(RDMA_CQE_VLAN, 0, 23, 1)
`RDMA_FIELD(RDMA_CQE_IPV6, 0, 22, 1)
`RDMA_FIELD(RDMA_CQE_CQE_FORMAT, 0, 20, 2)
`RDMA_FIELD(RDMA_CQE_RESIZE_CQE, 0, 19, 1)
`RDMA_FIELD(RDMA_CQE_UD_MC, 0, 18, 1)
`RDMA_FIELD(RDMA_CQE_QPN, 0, 0, 18)
`RDMA_FIELD(RDMA_CQE_IMMDT_DATA, 8, 32, 32)
`RDMA_FIELD(RDMA_CQE_PAYLOAD_LEN, 8, 0, 32)
`RDMA_FIELD(RDMA_CQE_SIGNATURE, 16, 56, 8)
`RDMA_FIELD(RDMA_CQE_RC_REMOTE_SYNDROME, 16, 48, 8)
`RDMA_FIELD(RDMA_CQE_UD_SRC_QPN, 16, 32, 24)
`RDMA_FIELD(RDMA_CQE_RQE_CPL, 16, 31, 1)
`RDMA_FIELD(RDMA_CQE_SRFQN, 16, 16, 12)
`RDMA_FIELD(RDMA_CQE_SRFQE_WRAP, 16, 15, 1)
`RDMA_FIELD(RDMA_CQE_SRFQE_INDEX, 16, 0, 15)
`RDMA_FIELD(RDMA_CQE_UD_SMAC, 24, 16, 48)
`RDMA_FIELD(RDMA_CQE_UD_VLAN_TAG, 24, 0, 16)

// CQE transport/receive variants are an authority gate for overlay fields.
// The default RC value preserves existing callers; a codec may be switched to
// UD or RQ/SRFQ explicitly before decoding a raw image.
typedef enum bit [1:0] {
  RDMA_CQE_VARIANT_RC = 2'd0,
  RDMA_CQE_VARIANT_UD = 2'd1,
  RDMA_CQE_VARIANT_RQ_SRFQ = 2'd2
} rdma_cqe_variant_e;

localparam bit [63:0] RDMA_CQE_QWORD0_UNION_MASK = 64'hffff_ffff_ffff_ffff;
localparam bit [63:0] RDMA_CQE_QWORD1_MASK = 64'hffff_ffff_ffff_ffff;
localparam bit [63:0] RDMA_CQE_QWORD2_RC_MASK = 64'hffff_0000_0000_0000;
localparam bit [63:0] RDMA_CQE_QWORD2_UD_MASK = 64'hffff_ffff_0000_0000;
localparam bit [63:0] RDMA_CQE_QWORD2_RQ_SRFQ_MASK = 64'hff00_0000_8fff_ffff;
// wr.h exposes qword2 as three physical overlay views.  The only wire
// coordinates absent from all views are bits [30:28]; all other union bits
// are driver-owned and must survive a raw CQE decode even when the caller has
// not yet selected a semantic transport variant.
localparam bit [63:0] RDMA_CQE_QWORD2_UNION_MASK = 64'hffff_ffff_8fff_ffff;
localparam bit [63:0] RDMA_CQE_QWORD3_UD_MASK = 64'hffff_ffff_ffff_ffff;
localparam int unsigned RDMA_CQE_64B_PAYLOAD_BYTE_OFFSET = 32;
localparam int unsigned RDMA_CQE_64B_PAYLOAD_BYTES = 32;
localparam int unsigned RDMA_CQE_128B_PAYLOAD_BYTE_OFFSET = 0;
localparam int unsigned RDMA_CQE_128B_PAYLOAD_BYTES = 64;

`RDMA_FIELD(RDMA_CEQE_VALID, 0, 63, 1)
// defs.h:66-73, CEQE qword0 common and URC selector fields.
`RDMA_FIELD(RDMA_CEQE_URC_FLAG, 0, 62, 1)
`RDMA_FIELD(RDMA_CEQE_QPN, 0, 40, 21)
`RDMA_FIELD(RDMA_CEQE_URC_SQ_CQE_VALID, 0, 39, 1)
`RDMA_FIELD(RDMA_CEQE_URC_RQ_CQE_VALID, 0, 38, 1)
`RDMA_FIELD(RDMA_CEQE_CQN, 0, 16, 21)
`RDMA_FIELD(RDMA_CEQE_ECODE, 0, 8, 8)
`RDMA_FIELD(RDMA_CEQE_PKT_OPCODE, 0, 0, 8)
// defs.h:77-85, CEQE URC qword1 abnormal completion fields.
`RDMA_FIELD(RDMA_CEQE_URC_ABNML_CQE_TYPE, 8, 56, 2)
`RDMA_FIELD(RDMA_CEQE_URC_ABNML_CQE_REMOTE_ECODE, 8, 48, 8)
`RDMA_FIELD(RDMA_CEQE_URC_ABNML_CQE_WQE_IDX_WRAP, 8, 47, 1)
`RDMA_FIELD(RDMA_CEQE_URC_ABNML_CQE_WQE_IDX, 8, 32, 15)
`RDMA_FIELD(RDMA_CEQE_URC_HW_CPL_SQ_WQE_IDX_WRAP, 8, 31, 1)
`RDMA_FIELD(RDMA_CEQE_URC_HW_CPL_SQ_WQE_IDX, 8, 16, 15)
`RDMA_FIELD(RDMA_CEQE_URC_HW_CPL_RQ_WQE_IDX_WRAP, 8, 15, 1)
`RDMA_FIELD(RDMA_CEQE_URC_HW_CPL_RQ_WQE_IDX, 8, 0, 15)
`RDMA_FIELD(RDMA_CEQE_CQ_PI_WRAP, 8, 23, 1)
`RDMA_FIELD(RDMA_CEQE_CQ_PI, 8, 0, 16)
// Driver union masks are kept beside the coordinates so codec and checker
// review the same fail-closed ownership boundary.
localparam bit [63:0] RDMA_CEQE_QWORD0_UNION_MASK = 64'hdfff_ffdf_ffff_ffff;
localparam bit [63:0] RDMA_CEQE_QWORD0_RC_MASK = 64'h9fff_ff1f_ffff_ffff;
localparam bit [63:0] RDMA_CEQE_QWORD1_RC_MASK = 64'h0000_0000_0080_ffff;
localparam bit [63:0] RDMA_CEQE_QWORD1_URC_MASK = 64'h03ff_ffff_ffff_ffff;

`RDMA_FIELD(RDMA_AEQE_VALID, 0, 63, 1)
`RDMA_FIELD(RDMA_AEQE_QP_ST, 0, 60, 3)
// defs.h:100-109, AEQE flags, abnormal type and split CQN/EQN fields.
`RDMA_FIELD(RDMA_AEQE_SRFQ_EN, 0, 59, 1)
`RDMA_FIELD(RDMA_AEQE_OVERFLOW_FLAG, 0, 58, 1)
`RDMA_FIELD(RDMA_AEQE_URC_FLAG, 0, 57, 1)
`RDMA_FIELD(RDMA_AEQE_CQ_INVALID_FLAG, 0, 56, 1)
`RDMA_FIELD(RDMA_AEQE_URC_ABNML_CQE_TYPE, 0, 54, 2)
`RDMA_FIELD(RDMA_AEQE_CQN_EQN_HIGH, 0, 40, 13)
`RDMA_FIELD(RDMA_AEQE_PKT_OPCODE, 0, 32, 8)
`RDMA_FIELD(RDMA_AEQE_ECODE, 0, 24, 8)
`RDMA_FIELD(RDMA_AEQE_CQN_EQN_LOW, 0, 18, 6)
`RDMA_FIELD(RDMA_AEQE_QPN, 0, 0, 18)
// defs.h:110-114, AEQE URC/queue fields in qword1.
`RDMA_FIELD(RDMA_AEQE_URC_REMOTE_ECODE, 8, 56, 8)
`RDMA_FIELD(RDMA_AEQE_QUEUE_WQE_IDX_WRAP, 8, 55, 1)
`RDMA_FIELD(RDMA_AEQE_WQE_WRAP, 8, 55, 1)
`RDMA_FIELD(RDMA_AEQE_SRFQN, 8, 16, 12)
`RDMA_FIELD(RDMA_AEQE_SRFQE_IDX, 8, 0, 16)
`RDMA_FIELD(RDMA_AEQE_WQE_INDEX, 8, 32, 23)
localparam int unsigned RDMA_AEQE_CQN_EQN_LSHIFT = 6;
localparam bit [63:0] RDMA_AEQE_QWORD0_MASK = 64'hffdf_ffff_ffff_ffff;
localparam bit [63:0] RDMA_AEQE_QWORD1_MASK = 64'hffff_ffff_0fff_ffff;

// Doorbell payload fields. All payloads are one logical 64-bit word.
`RDMA_FIELD(RDMA_CMQ_DB_PI, 0, 32, 5)
`RDMA_FIELD(RDMA_CMQ_DB_POLARITY, 0, 37, 1)
`RDMA_FIELD(RDMA_NOTIFY_RQ_PI_WRAP, 0, 47, 1)
`RDMA_FIELD(RDMA_NOTIFY_RQ_PI, 0, 32, 15)
`RDMA_FIELD(RDMA_NOTIFY_RQ_ICOS, 0, 21, 3)
`RDMA_FIELD(RDMA_NOTIFY_RQ_QPN, 0, 0, 21)
`RDMA_FIELD(RDMA_NOTIFY_SRFQ_WRAP, 0, 47, 1)
`RDMA_FIELD(RDMA_NOTIFY_SRFQ_PI, 0, 32, 15)
`RDMA_FIELD(RDMA_NOTIFY_SRFQN, 0, 0, 16)
`RDMA_FIELD(RDMA_NOTIFY_SRQ_LIMIT_INVALID, 0, 62, 1)
`RDMA_FIELD(RDMA_NOTIFY_SRQ_PI_INVALID, 0, 63, 1)
`RDMA_FIELD(RDMA_NOTIFY_SRQ_LIMIT, 0, 18, 14)
`RDMA_FIELD(RDMA_NOTIFY_SRQ_ARM_SN, 0, 16, 2)
`RDMA_FIELD(RDMA_NOTIFY_CQ_CI_INVALID, 0, 63, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_ARM_INVALID, 0, 62, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_ARM, 0, 61, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_URC, 0, 60, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_ARM_ST, 0, 58, 2)
`RDMA_FIELD(RDMA_NOTIFY_CQ_ARM_SN, 0, 56, 2)
`RDMA_FIELD(RDMA_NOTIFY_CQ_CI_WRAP, 0, 47, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_CI, 0, 24, 23)
`RDMA_FIELD(RDMA_NOTIFY_CQ_URC_SQ_WRAP, 0, 55, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_URC_SQ_CI, 0, 40, 15)
`RDMA_FIELD(RDMA_NOTIFY_CQ_URC_RQ_WRAP, 0, 39, 1)
`RDMA_FIELD(RDMA_NOTIFY_CQ_URC_RQ_CI, 0, 24, 15)
`RDMA_FIELD(RDMA_NOTIFY_CQ_HOST_ID, 0, 21, 3)
`RDMA_FIELD(RDMA_NOTIFY_CQ_CQN, 0, 0, 21)
`RDMA_FIELD(RDMA_NOTIFY_CEQ_CI_WRAP, 0, 50, 1)
`RDMA_FIELD(RDMA_NOTIFY_CEQ_CI, 0, 32, 18)
`RDMA_FIELD(RDMA_NOTIFY_CEQ_CEQN, 0, 0, 22)
`RDMA_FIELD(RDMA_NOTIFY_AEQ_CI_WRAP, 0, 50, 1)
`RDMA_FIELD(RDMA_NOTIFY_AEQ_CI, 0, 32, 18)
`RDMA_FIELD(RDMA_NOTIFY_AEQ_AEQN, 0, 0, 12)
`RDMA_FIELD(RDMA_NOTIFY_QP_DST_PORT, 0, 48, 4)
`RDMA_FIELD(RDMA_NOTIFY_QP_SN, 0, 40, 8)
`RDMA_FIELD(RDMA_NOTIFY_QP_DB_TYPE, 0, 36, 4)
`RDMA_FIELD(RDMA_NOTIFY_QP_ICOS, 0, 21, 3)
`RDMA_FIELD(RDMA_NOTIFY_QP_QPN, 0, 0, 21)

`undef RDMA_FIELD

`include "rdma/rdma_image_masks.svh"
